/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apron_Abstract0 */

#ifndef _Included_apron_Abstract0
#define _Included_apron_Abstract0
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     apron_Abstract0
 * Method:    init
 * Signature: (Lapron/Manager;Lapron/Abstract0;)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_init__Lapron_Manager_2Lapron_Abstract0_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    init
 * Signature: (Lapron/Manager;IIZ)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_init__Lapron_Manager_2IIZ
  (JNIEnv *, jobject, jobject, jint, jint, jboolean);

/*
 * Class:     apron_Abstract0
 * Method:    init
 * Signature: (Lapron/Manager;II[Lapron/Interval;)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_init__Lapron_Manager_2II_3Lapron_Interval_2
  (JNIEnv *, jobject, jobject, jint, jint, jobjectArray);

/*
 * Class:     apron_Abstract0
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_finalize
  (JNIEnv *, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    class_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_class_1init
  (JNIEnv *, jclass);

/*
 * Class:     apron_Abstract0
 * Method:    getSize
 * Signature: (Lapron/Manager;)I
 */
JNIEXPORT jint JNICALL Java_apron_Abstract0_getSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    hashCode
 * Signature: (Lapron/Manager;)I
 */
JNIEXPORT jint JNICALL Java_apron_Abstract0_hashCode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    getDimension
 * Signature: (Lapron/Manager;)Lapron/Dimension;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_getDimension
  (JNIEnv *, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    getCreationManager
 * Signature: ()Lapron/Manager;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_getCreationManager
  (JNIEnv *, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    getBound
 * Signature: (Lapron/Manager;Lapron/Linexpr0;)Lapron/Interval;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_getBound__Lapron_Manager_2Lapron_Linexpr0_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    getBound
 * Signature: (Lapron/Manager;Lapron/Texpr0Intern;)Lapron/Interval;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_getBound__Lapron_Manager_2Lapron_Texpr0Intern_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    getBound
 * Signature: (Lapron/Manager;I)Lapron/Interval;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_getBound__Lapron_Manager_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     apron_Abstract0
 * Method:    toLincons
 * Signature: (Lapron/Manager;)[Lapron/Lincons0;
 */
JNIEXPORT jobjectArray JNICALL Java_apron_Abstract0_toLincons
  (JNIEnv *, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    toTcons
 * Signature: (Lapron/Manager;)[Lapron/Tcons0;
 */
JNIEXPORT jobjectArray JNICALL Java_apron_Abstract0_toTcons
  (JNIEnv *, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    toBox
 * Signature: (Lapron/Manager;)[Lapron/Interval;
 */
JNIEXPORT jobjectArray JNICALL Java_apron_Abstract0_toBox
  (JNIEnv *, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    toGenerator
 * Signature: (Lapron/Manager;)[Lapron/Generator0;
 */
JNIEXPORT jobjectArray JNICALL Java_apron_Abstract0_toGenerator
  (JNIEnv *, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    isBottom
 * Signature: (Lapron/Manager;)Z
 */
JNIEXPORT jboolean JNICALL Java_apron_Abstract0_isBottom
  (JNIEnv *, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    isTop
 * Signature: (Lapron/Manager;)Z
 */
JNIEXPORT jboolean JNICALL Java_apron_Abstract0_isTop
  (JNIEnv *, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    isIncluded
 * Signature: (Lapron/Manager;Lapron/Abstract0;)Z
 */
JNIEXPORT jboolean JNICALL Java_apron_Abstract0_isIncluded
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    isEqual
 * Signature: (Lapron/Manager;Lapron/Abstract0;)Z
 */
JNIEXPORT jboolean JNICALL Java_apron_Abstract0_isEqual
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    satisfy
 * Signature: (Lapron/Manager;Lapron/Lincons0;)Z
 */
JNIEXPORT jboolean JNICALL Java_apron_Abstract0_satisfy__Lapron_Manager_2Lapron_Lincons0_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    satisfy
 * Signature: (Lapron/Manager;Lapron/Tcons0;)Z
 */
JNIEXPORT jboolean JNICALL Java_apron_Abstract0_satisfy__Lapron_Manager_2Lapron_Tcons0_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    satisfy
 * Signature: (Lapron/Manager;ILapron/Interval;)Z
 */
JNIEXPORT jboolean JNICALL Java_apron_Abstract0_satisfy__Lapron_Manager_2ILapron_Interval_2
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    isDimensionUnconstrained
 * Signature: (Lapron/Manager;I)Z
 */
JNIEXPORT jboolean JNICALL Java_apron_Abstract0_isDimensionUnconstrained
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     apron_Abstract0
 * Method:    minimize
 * Signature: (Lapron/Manager;)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_minimize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    canonicalize
 * Signature: (Lapron/Manager;)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_canonicalize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    approximate
 * Signature: (Lapron/Manager;I)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_approximate
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     apron_Abstract0
 * Method:    meetCopy
 * Signature: (Lapron/Manager;Lapron/Abstract0;)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_meetCopy__Lapron_Manager_2Lapron_Abstract0_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    meet
 * Signature: (Lapron/Manager;[Lapron/Abstract0;)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_meet__Lapron_Manager_2_3Lapron_Abstract0_2
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     apron_Abstract0
 * Method:    meet
 * Signature: (Lapron/Manager;Lapron/Abstract0;)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_meet__Lapron_Manager_2Lapron_Abstract0_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    joinCopy
 * Signature: (Lapron/Manager;Lapron/Abstract0;)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_joinCopy
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    join
 * Signature: (Lapron/Manager;[Lapron/Abstract0;)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_join__Lapron_Manager_2_3Lapron_Abstract0_2
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     apron_Abstract0
 * Method:    join
 * Signature: (Lapron/Manager;Lapron/Abstract0;)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_join__Lapron_Manager_2Lapron_Abstract0_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    meetCopy
 * Signature: (Lapron/Manager;[Lapron/Lincons0;)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_meetCopy__Lapron_Manager_2_3Lapron_Lincons0_2
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     apron_Abstract0
 * Method:    meetCopy
 * Signature: (Lapron/Manager;[Lapron/Tcons0;)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_meetCopy__Lapron_Manager_2_3Lapron_Tcons0_2
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     apron_Abstract0
 * Method:    meet
 * Signature: (Lapron/Manager;[Lapron/Lincons0;)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_meet__Lapron_Manager_2_3Lapron_Lincons0_2
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     apron_Abstract0
 * Method:    meet
 * Signature: (Lapron/Manager;[Lapron/Tcons0;)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_meet__Lapron_Manager_2_3Lapron_Tcons0_2
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     apron_Abstract0
 * Method:    addRayCopy
 * Signature: (Lapron/Manager;[Lapron/Generator0;)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_addRayCopy
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     apron_Abstract0
 * Method:    addRay
 * Signature: (Lapron/Manager;[Lapron/Generator0;)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_addRay
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     apron_Abstract0
 * Method:    assign
 * Signature: (Lapron/Manager;[I[Lapron/Linexpr0;Lapron/Abstract0;)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_assign__Lapron_Manager_2_3I_3Lapron_Linexpr0_2Lapron_Abstract0_2
  (JNIEnv *, jobject, jobject, jintArray, jobjectArray, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    assignCopy
 * Signature: (Lapron/Manager;[I[Lapron/Linexpr0;Lapron/Abstract0;)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_assignCopy__Lapron_Manager_2_3I_3Lapron_Linexpr0_2Lapron_Abstract0_2
  (JNIEnv *, jobject, jobject, jintArray, jobjectArray, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    assign
 * Signature: (Lapron/Manager;[I[Lapron/Texpr0Intern;Lapron/Abstract0;)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_assign__Lapron_Manager_2_3I_3Lapron_Texpr0Intern_2Lapron_Abstract0_2
  (JNIEnv *, jobject, jobject, jintArray, jobjectArray, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    assignCopy
 * Signature: (Lapron/Manager;[I[Lapron/Texpr0Intern;Lapron/Abstract0;)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_assignCopy__Lapron_Manager_2_3I_3Lapron_Texpr0Intern_2Lapron_Abstract0_2
  (JNIEnv *, jobject, jobject, jintArray, jobjectArray, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    substitute
 * Signature: (Lapron/Manager;[I[Lapron/Linexpr0;Lapron/Abstract0;)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_substitute__Lapron_Manager_2_3I_3Lapron_Linexpr0_2Lapron_Abstract0_2
  (JNIEnv *, jobject, jobject, jintArray, jobjectArray, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    substituteCopy
 * Signature: (Lapron/Manager;[I[Lapron/Linexpr0;Lapron/Abstract0;)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_substituteCopy__Lapron_Manager_2_3I_3Lapron_Linexpr0_2Lapron_Abstract0_2
  (JNIEnv *, jobject, jobject, jintArray, jobjectArray, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    substitute
 * Signature: (Lapron/Manager;[I[Lapron/Texpr0Intern;Lapron/Abstract0;)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_substitute__Lapron_Manager_2_3I_3Lapron_Texpr0Intern_2Lapron_Abstract0_2
  (JNIEnv *, jobject, jobject, jintArray, jobjectArray, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    substituteCopy
 * Signature: (Lapron/Manager;[I[Lapron/Texpr0Intern;Lapron/Abstract0;)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_substituteCopy__Lapron_Manager_2_3I_3Lapron_Texpr0Intern_2Lapron_Abstract0_2
  (JNIEnv *, jobject, jobject, jintArray, jobjectArray, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    forgetCopy
 * Signature: (Lapron/Manager;[IZ)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_forgetCopy
  (JNIEnv *, jobject, jobject, jintArray, jboolean);

/*
 * Class:     apron_Abstract0
 * Method:    forget
 * Signature: (Lapron/Manager;[IZ)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_forget
  (JNIEnv *, jobject, jobject, jintArray, jboolean);

/*
 * Class:     apron_Abstract0
 * Method:    addDimensionsCopy
 * Signature: (Lapron/Manager;Lapron/Dimchange;Z)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_addDimensionsCopy
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     apron_Abstract0
 * Method:    addDimensions
 * Signature: (Lapron/Manager;Lapron/Dimchange;Z)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_addDimensions
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     apron_Abstract0
 * Method:    removeDimensionsCopy
 * Signature: (Lapron/Manager;Lapron/Dimchange;)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_removeDimensionsCopy
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    removeDimensions
 * Signature: (Lapron/Manager;Lapron/Dimchange;)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_removeDimensions
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    permuteDimensionsCopy
 * Signature: (Lapron/Manager;Lapron/Dimperm;)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_permuteDimensionsCopy
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    permuteDimensions
 * Signature: (Lapron/Manager;Lapron/Dimperm;)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_permuteDimensions
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    expandCopy
 * Signature: (Lapron/Manager;II)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_expandCopy
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     apron_Abstract0
 * Method:    expand
 * Signature: (Lapron/Manager;II)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_expand
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     apron_Abstract0
 * Method:    foldCopy
 * Signature: (Lapron/Manager;[I)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_foldCopy
  (JNIEnv *, jobject, jobject, jintArray);

/*
 * Class:     apron_Abstract0
 * Method:    fold
 * Signature: (Lapron/Manager;[I)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_fold
  (JNIEnv *, jobject, jobject, jintArray);

/*
 * Class:     apron_Abstract0
 * Method:    widening
 * Signature: (Lapron/Manager;Lapron/Abstract0;)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_widening
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    wideningThreshold
 * Signature: (Lapron/Manager;Lapron/Abstract0;[Lapron/Lincons0;)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_wideningThreshold
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     apron_Abstract0
 * Method:    closureCopy
 * Signature: (Lapron/Manager;)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_closureCopy
  (JNIEnv *, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    closure
 * Signature: (Lapron/Manager;)V
 */
JNIEXPORT void JNICALL Java_apron_Abstract0_closure
  (JNIEnv *, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    serialize
 * Signature: (Lapron/Manager;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_apron_Abstract0_serialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     apron_Abstract0
 * Method:    deserialize
 * Signature: (Lapron/Manager;[B)Lapron/Abstract0;
 */
JNIEXPORT jobject JNICALL Java_apron_Abstract0_deserialize
  (JNIEnv *, jclass, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
