/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apron_Dimperm */

#ifndef _Included_apron_Dimperm
#define _Included_apron_Dimperm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     apron_Dimperm
 * Method:    init
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_apron_Dimperm_init___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     apron_Dimperm
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_apron_Dimperm_init__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     apron_Dimperm
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_apron_Dimperm_finalize
  (JNIEnv *, jobject);

/*
 * Class:     apron_Dimperm
 * Method:    class_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_apron_Dimperm_class_1init
  (JNIEnv *, jclass);

/*
 * Class:     apron_Dimperm
 * Method:    setId
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_apron_Dimperm_setId
  (JNIEnv *, jobject);

/*
 * Class:     apron_Dimperm
 * Method:    setElem
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_apron_Dimperm_setElem
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     apron_Dimperm
 * Method:    getElem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_apron_Dimperm_getElem
  (JNIEnv *, jobject, jint);

/*
 * Class:     apron_Dimperm
 * Method:    getSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_apron_Dimperm_getSize
  (JNIEnv *, jobject);

/*
 * Class:     apron_Dimperm
 * Method:    getContents
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_apron_Dimperm_getContents
  (JNIEnv *, jobject);

/*
 * Class:     apron_Dimperm
 * Method:    invert
 * Signature: ()Lapron/Dimperm;
 */
JNIEXPORT jobject JNICALL Java_apron_Dimperm_invert
  (JNIEnv *, jobject);

/*
 * Class:     apron_Dimperm
 * Method:    compose
 * Signature: (Lapron/Dimperm;)Lapron/Dimperm;
 */
JNIEXPORT jobject JNICALL Java_apron_Dimperm_compose
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
