/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apron_Dimchange */

#ifndef _Included_apron_Dimchange
#define _Included_apron_Dimchange
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     apron_Dimchange
 * Method:    init
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_apron_Dimchange_init
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     apron_Dimchange
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_apron_Dimchange_finalize
  (JNIEnv *, jobject);

/*
 * Class:     apron_Dimchange
 * Method:    class_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_apron_Dimchange_class_1init
  (JNIEnv *, jclass);

/*
 * Class:     apron_Dimchange
 * Method:    getDimension
 * Signature: ()Lapron/Dimension;
 */
JNIEXPORT jobject JNICALL Java_apron_Dimchange_getDimension
  (JNIEnv *, jobject);

/*
 * Class:     apron_Dimchange
 * Method:    getContents
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_apron_Dimchange_getContents
  (JNIEnv *, jobject);

/*
 * Class:     apron_Dimchange
 * Method:    afterAdd
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_apron_Dimchange_afterAdd
  (JNIEnv *, jobject, jint);

/*
 * Class:     apron_Dimchange
 * Method:    afterRemove
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_apron_Dimchange_afterRemove
  (JNIEnv *, jobject, jint);

/*
 * Class:     apron_Dimchange
 * Method:    addInvert
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_apron_Dimchange_addInvert
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
