/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apron_Lincons0 */

#ifndef _Included_apron_Lincons0
#define _Included_apron_Lincons0
#ifdef __cplusplus
extern "C" {
#endif
#undef apron_Lincons0_EQ
#define apron_Lincons0_EQ 0L
#undef apron_Lincons0_SUPEQ
#define apron_Lincons0_SUPEQ 1L
#undef apron_Lincons0_SUP
#define apron_Lincons0_SUP 2L
#undef apron_Lincons0_EQMOD
#define apron_Lincons0_EQMOD 3L
#undef apron_Lincons0_DISEQ
#define apron_Lincons0_DISEQ 4L
/*
 * Class:     apron_Lincons0
 * Method:    isUnsat
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_apron_Lincons0_isUnsat
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
