/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gmp_Mpz */

#ifndef _Included_gmp_Mpz
#define _Included_gmp_Mpz
#ifdef __cplusplus
extern "C" {
#endif
#undef gmp_Mpz_infinite
#define gmp_Mpz_infinite -1L
/*
 * Class:     gmp_Mpz
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_init
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    init_set
 * Signature: (Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_init_1set__Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    init_set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_init_1set__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    init_set
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_init_1set__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     gmp_Mpz
 * Method:    init_set
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_init_1set__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     gmp_Mpz
 * Method:    set
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_set__I_3B
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     gmp_Mpz
 * Method:    byteArrayValue
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_gmp_Mpz_byteArrayValue
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_finalize
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    class_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_class_1init
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpz
 * Method:    set
 * Signature: (Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_set__Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_set__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    set
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_set__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     gmp_Mpz
 * Method:    set
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_set__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     gmp_Mpz
 * Method:    intValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_intValue
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    doubleValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_gmp_Mpz_doubleValue
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    doubleExponentValue
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_gmp_Mpz_doubleExponentValue
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     gmp_Mpz
 * Method:    toString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gmp_Mpz_toString
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    add
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_add__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    add
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_add__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    sub
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_sub__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    sub
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_sub__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    sub
 * Signature: (ILgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_sub__ILgmp_Mpz_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    mul
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_mul__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    mul
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_mul__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    addMul
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_addMul__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    addMul
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_addMul__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    subMul
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_subMul__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    subMul
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_subMul__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    mul2exp
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_mul2exp
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    neg
 * Signature: (Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_neg
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    abs
 * Signature: (Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_abs
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    cdivQ
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_cdivQ__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    cdivR
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_cdivR__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    cdivQR
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_cdivQR__Lgmp_Mpz_2Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    cdivQ
 * Signature: (Lgmp/Mpz;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_cdivQ__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    cdivR
 * Signature: (Lgmp/Mpz;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_cdivR__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    cdivQR
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_cdivQR__Lgmp_Mpz_2Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    cdivR
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_cdivR__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    cdivQ2exp
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_cdivQ2exp
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    cdivR2exp
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_cdivR2exp
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    fdivQ
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_fdivQ__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    fdivR
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_fdivR__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    fdivQR
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_fdivQR__Lgmp_Mpz_2Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    fdivQ
 * Signature: (Lgmp/Mpz;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_fdivQ__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    fdivR
 * Signature: (Lgmp/Mpz;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_fdivR__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    fdivQR
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_fdivQR__Lgmp_Mpz_2Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    fdivR
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_fdivR__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    fdivQ2exp
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_fdivQ2exp
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    fdivR2exp
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_fdivR2exp
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    tdivQ
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_tdivQ__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    tdivR
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_tdivR__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    tdivQR
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_tdivQR__Lgmp_Mpz_2Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    tdivQ
 * Signature: (Lgmp/Mpz;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_tdivQ__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    tdivR
 * Signature: (Lgmp/Mpz;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_tdivR__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    tdivQR
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_tdivQR__Lgmp_Mpz_2Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    tdivR
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_tdivR__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    tdivQ2exp
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_tdivQ2exp
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    tdivR2exp
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_tdivR2exp
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    mod
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_mod__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    mod
 * Signature: (Lgmp/Mpz;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_mod__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    divExact
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_divExact__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    divExact
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_divExact__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    isDivisible
 * Signature: (Lgmp/Mpz;)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpz_isDivisible__Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    isDivisible
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpz_isDivisible__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    isDivisible2exp
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpz_isDivisible2exp
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    isCongruent
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpz_isCongruent__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    isCongruent
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpz_isCongruent__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gmp_Mpz
 * Method:    isCongruent2exp
 * Signature: (Lgmp/Mpz;I)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpz_isCongruent2exp
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    pow
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_pow__Lgmp_Mpz_2Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    pow
 * Signature: (Lgmp/Mpz;ILgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_pow__Lgmp_Mpz_2ILgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    pow
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_pow__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    pow
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_pow__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gmp_Mpz
 * Method:    root
 * Signature: (Lgmp/Mpz;I)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpz_root__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    root
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_root__Lgmp_Mpz_2Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    sqrt
 * Signature: (Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_sqrt__Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    sqrt
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_sqrt__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    isPerfectPower
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpz_isPerfectPower
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    isPerfectSquare
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpz_isPerfectSquare
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    isProbabPrime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_isProbabPrime
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    nextPrime
 * Signature: (Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_nextPrime
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    gcd
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_gcd__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    gcd
 * Signature: (Lgmp/Mpz;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_gcd__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    gcd
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_gcd__Lgmp_Mpz_2Lgmp_Mpz_2Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    lcm
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_lcm__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    lcm
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_lcm__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    invert
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpz_invert
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    jacobi
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_jacobi
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    legendre
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_legendre
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    kronecker
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_kronecker__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    kronecker
 * Signature: (Lgmp/Mpz;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_kronecker__Lgmp_Mpz_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    kronecker
 * Signature: (ILgmp/Mpz;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_kronecker__ILgmp_Mpz_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    remove
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_remove
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    fac
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_fac
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    bin
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_bin__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    bin
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_bin__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gmp_Mpz
 * Method:    fib
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_fib__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    fib
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_fib__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    lucnum
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_lucnum__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    lucnum
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_lucnum__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    cmp
 * Signature: (Lgmp/Mpz;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_cmp__Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    cmp
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_cmp__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    cmp
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_cmp__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     gmp_Mpz
 * Method:    cmpAbs
 * Signature: (Lgmp/Mpz;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_cmpAbs__Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    cmpAbs
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_cmpAbs__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    cmpAbs
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_cmpAbs__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     gmp_Mpz
 * Method:    sgn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_sgn
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    hashCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_hashCode
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    and
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_and
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    or
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_or
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    xor
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_xor
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    not
 * Signature: (Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_not
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    popCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_popCount
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    hamDist
 * Signature: (Lgmp/Mpz;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_hamDist
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    scan0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_scan0
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    scan1
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_scan1
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    setBit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_setBit
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    clrBit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_clrBit
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    notBit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_notBit
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    tstBit
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpz_tstBit
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    fitsInt
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpz_fitsInt
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    isOdd
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpz_isOdd
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    isEven
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpz_isEven
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    sizeInBase
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_sizeInBase
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpz_size
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    randomBits
 * Signature: (Lgmp/RandState;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_randomBits
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpz
 * Method:    random
 * Signature: (Lgmp/RandState;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_random
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpz
 * Method:    rRandomBits
 * Signature: (Lgmp/RandState;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpz_rRandomBits
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
