/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gmp_RandState */

#ifndef _Included_gmp_RandState
#define _Included_gmp_RandState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gmp_RandState
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_RandState_init__
  (JNIEnv *, jobject);

/*
 * Class:     gmp_RandState
 * Method:    init_mt
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_RandState_init_1mt
  (JNIEnv *, jobject);

/*
 * Class:     gmp_RandState
 * Method:    init_lc_2exp
 * Signature: (Lgmp/Mpz;II)V
 */
JNIEXPORT void JNICALL Java_gmp_RandState_init_1lc_12exp
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     gmp_RandState
 * Method:    init_lc_2exp_size
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gmp_RandState_init_1lc_12exp_1size
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_RandState
 * Method:    init
 * Signature: (Lgmp/RandState;)V
 */
JNIEXPORT void JNICALL Java_gmp_RandState_init__Lgmp_RandState_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_RandState
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_RandState_finalize
  (JNIEnv *, jobject);

/*
 * Class:     gmp_RandState
 * Method:    class_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_RandState_class_1init
  (JNIEnv *, jclass);

/*
 * Class:     gmp_RandState
 * Method:    Seed
 * Signature: (Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_RandState_Seed__Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_RandState
 * Method:    Seed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gmp_RandState_Seed__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_RandState
 * Method:    randomBits
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gmp_RandState_randomBits
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_RandState
 * Method:    randomInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gmp_RandState_randomInt
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
