/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gmp_Mpfr */

#ifndef _Included_gmp_Mpfr
#define _Included_gmp_Mpfr
#ifdef __cplusplus
extern "C" {
#endif
#undef gmp_Mpfr_RNDN
#define gmp_Mpfr_RNDN 0L
#undef gmp_Mpfr_RNDZ
#define gmp_Mpfr_RNDZ 1L
#undef gmp_Mpfr_RNDU
#define gmp_Mpfr_RNDU 2L
#undef gmp_Mpfr_RNDD
#define gmp_Mpfr_RNDD 3L
/*
 * Class:     gmp_Mpfr
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_init__
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_init__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    init_set
 * Signature: (Lgmp/Mpfr;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_init_1set__Lgmp_Mpfr_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    init_set
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_init_1set__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    init_set
 * Signature: (Lgmp/Mpz;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_init_1set__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    init_set
 * Signature: (DI)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_init_1set__DI
  (JNIEnv *, jobject, jdouble, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    init_set
 * Signature: (Lgmp/Mpq;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_init_1set__Lgmp_Mpq_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    init_set
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_init_1set__Ljava_lang_String_2II
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_finalize
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    class_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_class_1init
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    setDefaultPrec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_setDefaultPrec
  (JNIEnv *, jclass, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    getDefaultPrec
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_getDefaultPrec
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    setPrec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_setPrec
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    getPrec
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_getPrec
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    set
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_set__Lgmp_Mpfr_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    set
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_set__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    set
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_set__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    set
 * Signature: (Lgmp/Mpz;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_set__Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    set
 * Signature: (DI)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_set__DI
  (JNIEnv *, jobject, jdouble, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    set
 * Signature: (Lgmp/Mpq;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_set__Lgmp_Mpq_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    set
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_set__Ljava_lang_String_2II
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    setInf
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_setInf
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    setNaN
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_setNaN
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    intValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_intValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    doubleValue
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_gmp_Mpfr_doubleValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    doubleExponentValue
 * Signature: ([II)D
 */
JNIEXPORT jdouble JNICALL Java_gmp_Mpfr_doubleExponentValue
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    MpzValue
 * Signature: (I)Lgmp/Mpz;
 */
JNIEXPORT jobject JNICALL Java_gmp_Mpfr_MpzValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    MpzExponentValue
 * Signature: (Lgmp/Mpz;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_MpzExponentValue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    toString
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gmp_Mpfr_toString
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    fitsInt
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_fitsInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    add
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_add__Lgmp_Mpfr_2Lgmp_Mpfr_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    add
 * Signature: (Lgmp/Mpfr;II)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_add__Lgmp_Mpfr_2II
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    add
 * Signature: (Lgmp/Mpfr;DI)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_add__Lgmp_Mpfr_2DI
  (JNIEnv *, jobject, jobject, jdouble, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    add
 * Signature: (Lgmp/Mpfr;Lgmp/Mpz;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_add__Lgmp_Mpfr_2Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    add
 * Signature: (Lgmp/Mpfr;Lgmp/Mpq;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_add__Lgmp_Mpfr_2Lgmp_Mpq_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    sub
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_sub__Lgmp_Mpfr_2Lgmp_Mpfr_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    sub
 * Signature: (Lgmp/Mpfr;II)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_sub__Lgmp_Mpfr_2II
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    sub
 * Signature: (Lgmp/Mpfr;DI)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_sub__Lgmp_Mpfr_2DI
  (JNIEnv *, jobject, jobject, jdouble, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    sub
 * Signature: (Lgmp/Mpfr;Lgmp/Mpz;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_sub__Lgmp_Mpfr_2Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    sub
 * Signature: (Lgmp/Mpfr;Lgmp/Mpq;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_sub__Lgmp_Mpfr_2Lgmp_Mpq_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    sub
 * Signature: (ILgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_sub__ILgmp_Mpfr_2I
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    sub
 * Signature: (DLgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_sub__DLgmp_Mpfr_2I
  (JNIEnv *, jobject, jdouble, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    mul
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_mul__Lgmp_Mpfr_2Lgmp_Mpfr_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    mul
 * Signature: (Lgmp/Mpfr;II)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_mul__Lgmp_Mpfr_2II
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    mul
 * Signature: (Lgmp/Mpfr;DI)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_mul__Lgmp_Mpfr_2DI
  (JNIEnv *, jobject, jobject, jdouble, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    mul
 * Signature: (Lgmp/Mpfr;Lgmp/Mpz;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_mul__Lgmp_Mpfr_2Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    mul
 * Signature: (Lgmp/Mpfr;Lgmp/Mpq;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_mul__Lgmp_Mpfr_2Lgmp_Mpq_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    div
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_div__Lgmp_Mpfr_2Lgmp_Mpfr_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    div
 * Signature: (Lgmp/Mpfr;II)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_div__Lgmp_Mpfr_2II
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    div
 * Signature: (Lgmp/Mpfr;DI)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_div__Lgmp_Mpfr_2DI
  (JNIEnv *, jobject, jobject, jdouble, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    div
 * Signature: (Lgmp/Mpfr;Lgmp/Mpz;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_div__Lgmp_Mpfr_2Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    div
 * Signature: (Lgmp/Mpfr;Lgmp/Mpq;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_div__Lgmp_Mpfr_2Lgmp_Mpq_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    div
 * Signature: (ILgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_div__ILgmp_Mpfr_2I
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    div
 * Signature: (DLgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_div__DLgmp_Mpfr_2I
  (JNIEnv *, jobject, jdouble, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    sqrt
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_sqrt__Lgmp_Mpfr_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    sqrt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_sqrt__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    recSqrt
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_recSqrt
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    cbrt
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_cbrt
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    root
 * Signature: (Lgmp/Mpfr;II)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_root
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    pow
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_pow__Lgmp_Mpfr_2Lgmp_Mpfr_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    pow
 * Signature: (Lgmp/Mpfr;II)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_pow__Lgmp_Mpfr_2II
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    pow
 * Signature: (Lgmp/Mpfr;Lgmp/Mpz;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_pow__Lgmp_Mpfr_2Lgmp_Mpz_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    neg
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_neg
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    abs
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_abs
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    dim
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_dim
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    mul2exp
 * Signature: (Lgmp/Mpfr;II)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_mul2exp
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    div2exp
 * Signature: (Lgmp/Mpfr;II)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_div2exp
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    cmp
 * Signature: (Lgmp/Mpfr;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_cmp__Lgmp_Mpfr_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    cmp
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_cmp__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    cmp
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_cmp__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     gmp_Mpfr
 * Method:    cmp
 * Signature: (Lgmp/Mpz;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_cmp__Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    cmp
 * Signature: (Lgmp/Mpq;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_cmp__Lgmp_Mpq_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    cmp2exp
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_cmp2exp
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    cmpAbs
 * Signature: (Lgmp/Mpfr;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_cmpAbs
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    isNaN
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_isNaN
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    isInf
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_isInf
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    isNumber
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_isNumber
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    isZero
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_isZero
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    sgn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_sgn
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    isGreater
 * Signature: (Lgmp/Mpfr;)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_isGreater
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    isGreaterEqual
 * Signature: (Lgmp/Mpfr;)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_isGreaterEqual
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    isLess
 * Signature: (Lgmp/Mpfr;)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_isLess
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    isLessEqual
 * Signature: (Lgmp/Mpfr;)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_isLessEqual
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    isLessGreater
 * Signature: (Lgmp/Mpfr;)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_isLessGreater
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    isEqual
 * Signature: (Lgmp/Mpfr;)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_isEqual
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    isUnordered
 * Signature: (Lgmp/Mpfr;)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_isUnordered
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    hashCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_hashCode
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    log
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_log
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    log2
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_log2
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    log10
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_log10
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    exp
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_exp
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    exp2
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_exp2
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    exp10
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_exp10
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    cos
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_cos
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    sin
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_sin
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    tan
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_tan
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    sec
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_sec
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    csc
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_csc
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    cot
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_cot
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    sinCos
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_sinCos
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    acos
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_acos
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    asin
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_asin
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    atan
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_atan
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    atan2
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_atan2
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    cosh
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_cosh
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    sinh
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_sinh
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    sinhCosh
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_sinhCosh
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    sech
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_sech
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    csch
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_csch
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    coth
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_coth
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    acosh
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_acosh
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    asinh
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_asinh
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    atanh
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_atanh
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    fac
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_fac
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    log1p
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_log1p
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    expm1
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_expm1
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    eint
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_eint
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    li2
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_li2
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    gamma
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_gamma
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    lngamma
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_lngamma
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    lgamma
 * Signature: ([ILgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_lgamma
  (JNIEnv *, jobject, jintArray, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    zeta
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_zeta__Lgmp_Mpfr_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    zeta
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_zeta__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    erf
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_erf
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    erfc
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_erfc
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    j0
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_j0
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    j1
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_j1
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    jn
 * Signature: (ILgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_jn
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    y0
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_y0
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    y1
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_y1
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    yn
 * Signature: (ILgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_yn
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    fma
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_fma
  (JNIEnv *, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    fms
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_fms
  (JNIEnv *, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    agm
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_agm
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    hypot
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_hypot
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    constLog2
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_constLog2
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    constPi
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_constPi
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    constEuler
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_constEuler
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    constCatalan
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_constCatalan
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    freeCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_freeCache
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    sum
 * Signature: ([Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_sum
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    rint
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_rint
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    ceil
 * Signature: (Lgmp/Mpfr;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_ceil
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    floor
 * Signature: (Lgmp/Mpfr;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_floor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    round
 * Signature: (Lgmp/Mpfr;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_round
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    trunc
 * Signature: (Lgmp/Mpfr;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_trunc
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    rint_ceil
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_rint_1ceil
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    rint_floor
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_rint_1floor
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    rint_round
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_rint_1round
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    rint_trunc
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_rint_1trunc
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    frac
 * Signature: (Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_frac
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    modf
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_modf
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    fmod
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_fmod
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    remainder
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_remainder
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    remquo
 * Signature: ([ILgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_remquo
  (JNIEnv *, jobject, jintArray, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    isInteger
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_isInteger
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    precRound
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_precRound
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    canRound
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_canRound
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    toStringRndMode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gmp_Mpfr_toStringRndMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    nextToward
 * Signature: (Lgmp/Mpfr;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_nextToward
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    nextAbove
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_nextAbove
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    nextBelow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_nextBelow
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    min
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_min
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    max
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_max
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    getExp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_getExp
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    setExp
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_setExp
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    signBit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_signBit
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpfr
 * Method:    setSign
 * Signature: (Lgmp/Mpfr;ZI)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_setSign
  (JNIEnv *, jobject, jobject, jboolean, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    copySign
 * Signature: (Lgmp/Mpfr;Lgmp/Mpfr;I)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_copySign
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gmp_Mpfr_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    getPatches
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gmp_Mpfr_getPatches
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    getEmin
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_gmp_Mpfr_getEmin
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    getEmax
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_gmp_Mpfr_getEmax
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    setEmin
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_setEmin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gmp_Mpfr
 * Method:    setEmax
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_setEmax
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gmp_Mpfr
 * Method:    getEminMin
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_gmp_Mpfr_getEminMin
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    getEminMax
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_gmp_Mpfr_getEminMax
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    getEmaxMin
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_gmp_Mpfr_getEmaxMin
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    getEmaxMax
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_gmp_Mpfr_getEmaxMax
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    checkRange
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_checkRange
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    subNormalize
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_subNormalize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gmp_Mpfr
 * Method:    clearUnderflow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_clearUnderflow
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    clearOverflow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_clearOverflow
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    clearNaNFlag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_clearNaNFlag
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    clearInexFlag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_clearInexFlag
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    clearERangeFlag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_clearERangeFlag
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    setUnderflow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_setUnderflow
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    setOverflow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_setOverflow
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    setNaNFlag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_setNaNFlag
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    setInexFlag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_setInexFlag
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    setERangeFlag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpfr_setERangeFlag
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    isUnderflow
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_isUnderflow
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    isOverflow
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_isOverflow
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    isNaNFlag
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_isNaNFlag
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    isInexFlag
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_isInexFlag
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    isERangeFlag
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpfr_isERangeFlag
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpfr
 * Method:    random
 * Signature: (Lgmp/RandState;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpfr_random
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
