/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gmp_MpzRef */

#ifndef _Included_gmp_MpzRef
#define _Included_gmp_MpzRef
#ifdef __cplusplus
extern "C" {
#endif
#undef gmp_MpzRef_infinite
#define gmp_MpzRef_infinite -1L
/*
 * Class:     gmp_MpzRef
 * Method:    class_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_MpzRef_class_1init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
