/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gmp_Mpq */

#ifndef _Included_gmp_Mpq
#define _Included_gmp_Mpq
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gmp_Mpq
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_init
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_finalize
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    class_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_class_1init
  (JNIEnv *, jclass);

/*
 * Class:     gmp_Mpq
 * Method:    canonicalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_canonicalize
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    set
 * Signature: (Lgmp/Mpq;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_set__Lgmp_Mpq_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    set
 * Signature: (Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_set__Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    set
 * Signature: (Lgmp/Mpz;Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_set__Lgmp_Mpz_2Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    set
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_set__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gmp_Mpq
 * Method:    set
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_set__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     gmp_Mpq
 * Method:    set
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_set__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     gmp_Mpq
 * Method:    setNum
 * Signature: (Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_setNum__Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    setNum
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_setNum__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpq
 * Method:    setDen
 * Signature: (Lgmp/Mpz;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_setDen__Lgmp_Mpz_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    setDen
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_setDen__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpq
 * Method:    doubleValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_gmp_Mpq_doubleValue
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    toString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gmp_Mpq_toString
  (JNIEnv *, jobject, jint);

/*
 * Class:     gmp_Mpq
 * Method:    getNum
 * Signature: ()Lgmp/Mpz;
 */
JNIEXPORT jobject JNICALL Java_gmp_Mpq_getNum
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    getDen
 * Signature: ()Lgmp/Mpz;
 */
JNIEXPORT jobject JNICALL Java_gmp_Mpq_getDen
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    numRef
 * Signature: ()Lgmp/MpzRef;
 */
JNIEXPORT jobject JNICALL Java_gmp_Mpq_numRef
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    denRef
 * Signature: ()Lgmp/MpzRef;
 */
JNIEXPORT jobject JNICALL Java_gmp_Mpq_denRef
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    add
 * Signature: (Lgmp/Mpq;Lgmp/Mpq;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_add
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    sub
 * Signature: (Lgmp/Mpq;Lgmp/Mpq;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_sub
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    mul
 * Signature: (Lgmp/Mpq;Lgmp/Mpq;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_mul
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    mul2exp
 * Signature: (Lgmp/Mpq;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_mul2exp
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpq
 * Method:    div
 * Signature: (Lgmp/Mpq;Lgmp/Mpq;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_div
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    div2exp
 * Signature: (Lgmp/Mpq;I)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_div2exp
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     gmp_Mpq
 * Method:    neg
 * Signature: (Lgmp/Mpq;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_neg
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    abs
 * Signature: (Lgmp/Mpq;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_abs
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    inv
 * Signature: (Lgmp/Mpq;)V
 */
JNIEXPORT void JNICALL Java_gmp_Mpq_inv
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpq_size
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    cmp
 * Signature: (Lgmp/Mpq;)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpq_cmp__Lgmp_Mpq_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    cmp
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpq_cmp__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gmp_Mpq
 * Method:    sgn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpq_sgn
  (JNIEnv *, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    isEqual
 * Signature: (Lgmp/Mpq;)Z
 */
JNIEXPORT jboolean JNICALL Java_gmp_Mpq_isEqual
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gmp_Mpq
 * Method:    hashCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gmp_Mpq_hashCode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
